name: blog_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fpdart: ^1.1.0
  supabase_flutter: ^2.4.0
  flutter_bloc: ^8.1.5
  get_it: ^7.6.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
 

flutter:
  uses-material-design: true
